name: mural_cyanurito
description: "Dennis Mural Cyanurito"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  
  assets:
    - assets/images/
    - assets/test-images/
    - assets/title/
    
  fonts:
    - family: SignikaNegative
      fonts:
        - asset: fonts/SignikaNegative-Regular.ttf

  uses-material-design: true
